apiVersion: v1
kind: Service
metadata:
  name: {{ include "mimir-cardinality-analyzer.fullname" . }}
  labels:
    {{- include "mimir-cardinality-analyzer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "mimir-cardinality-analyzer.selectorLabels" . | nindent 4 }}
